/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package capaGui;

import capaDatos.DatosCliente;
import capaNegocio.NegocioCliente;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Johnny y karo
 */
public class Loguin extends javax.swing.JDialog {

    /**
     * Creates new form Loguin1
     */
    public Loguin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRutoLoguin = new javax.swing.JLabel();
        lblContraseñaLoguin = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        pswContraseñaLoguin = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtDigito = new javax.swing.JTextField();
        lblGuion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRutoLoguin.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblRutoLoguin.setText("Rut");

        lblContraseñaLoguin.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblContraseñaLoguin.setText("Contraseña");

        txtRut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });

        pswContraseñaLoguin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pswContraseñaLoguin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswContraseñaLoguinKeyTyped(evt);
            }
        });

        btnIngresar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtDigito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDigito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitoActionPerformed(evt);
            }
        });
        txtDigito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDigitoKeyTyped(evt);
            }
        });

        lblGuion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGuion.setText("-");

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loguin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnIngresar)
                        .addGap(68, 68, 68)
                        .addComponent(btnCancelar)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseñaLoguin)
                            .addComponent(lblRutoLoguin))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pswContraseñaLoguin, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGuion, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutoLoguin)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pswContraseñaLoguin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseñaLoguin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        } else {
            if (txtRut.getText().trim().length() > 7) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtRutKeyTyped

    private void pswContraseñaLoguinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswContraseñaLoguinKeyTyped
        if (this.pswContraseñaLoguin.getText().trim().length() > 20) {

            evt.consume();
        }
    }//GEN-LAST:event_pswContraseñaLoguinKeyTyped
    private int comparar;
    private String comparar2;
    private int a = 0;

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (this.txtRut.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Usuario",
                    "Error de Ingreso", JOptionPane.ERROR_MESSAGE);
            this.txtRut.requestFocus();
            return;
        }
        if (this.pswContraseñaLoguin.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la Contraseña",
                    "Error de Ingreso", JOptionPane.ERROR_MESSAGE);
            this.pswContraseñaLoguin.requestFocus();
            return;
        }
        

        NegocioCliente neg = new NegocioCliente();

        DatosCliente asd = neg.buscarDatos(Integer.parseInt(this.txtRut.getText().trim()));
        comparar = (Integer.parseInt(txtRut.getText()));
        comparar2 = (pswContraseñaLoguin.getText());


        if (comparar != asd.getRut()) {
            JOptionPane.showMessageDialog(this, "usuario no existe",
                    "Error de Ingreso", JOptionPane.ERROR_MESSAGE);
            this.txtRut.setText("");
            this.txtDigito.setText("");
            this.txtRut.requestFocus();
        } else {            
            ValidadRut();
        }
        if (!comparar2.equals(asd.getContraseña())) {
            JOptionPane.showMessageDialog(this, "Contraseña Incorrecta",
                    "Error de Ingreso", JOptionPane.ERROR_MESSAGE);
            this.pswContraseñaLoguin.setText("");
            this.pswContraseñaLoguin.requestFocus();
        } else {
            a = a + 2;
        }
        if (a == 3) {
            
            DatosCliente.Comparar = (asd.getNombre() +"  "+ asd.getApellido());
            DatosCliente.Comparar2 = (asd.getRut());
                        
            
            this.dispose();

            MenuUsuario dialog = new MenuUsuario(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        }



    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDigitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDigitoKeyTyped
        if ((evt.getKeyChar() < '0' || evt.getKeyChar() > '9')
                && (evt.getKeyChar() != 'k') && (evt.getKeyChar() != 'K')) {
            evt.consume();
        } else {
            if (txtDigito.getText().trim().length() > 0) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtDigitoKeyTyped

    private void txtDigitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Loguin dialog = new Loguin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblContraseñaLoguin;
    private javax.swing.JLabel lblGuion;
    private javax.swing.JLabel lblRutoLoguin;
    private javax.swing.JPasswordField pswContraseñaLoguin;
    private javax.swing.JTextField txtDigito;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables

    private void ValidadRut() {
        int suma = 0;
        int pond = 2;
        int largo = this.txtRut.getText().trim().length();
        int resto = 0;
        int digito = 0;
        String digVer = "";
        for (int i = largo - 1; i > -1; i--) {
            //System.out.println(this.txtRut.getText().charAt(i));
            suma = suma + (Integer.parseInt("" + this.txtRut.getText().charAt(i)) * pond);
            pond++;
            if (pond > 7) {
                pond = 2;
            }
        }
        //System.out.println("suma: " + suma);
        resto = suma % 11;
        digito = 11 - resto;
        if (digito == 10) {
            digVer = "k";
        } else if (digito == 11) {
            digVer = "0";
        } else {
            digVer = "" + digito;
        }
        if (!this.txtDigito.getText().equals(digVer)) {
            JOptionPane.showMessageDialog(this, "Rut incorrecto", "Error de ingreso", JOptionPane.WARNING_MESSAGE);
            this.txtDigito.requestFocus();
            
        }else
        {
            a = 1;
        }
    }
}
